namespace RPG.Stats
{
      public enum Stat
    {
        Health,
        ExperienceReward,
        ExperienceToLevelUp,
        MinDamage,
        MaxDamage,
        Mana,
        ManaRegenRate,
        TotalTraitPoints,
        BuyingDiscountPercentage,
        Defence,
        Helmet,
        HelmetNoHair,
        Mask,
        HelmetDodatek,
        Torse,
        Hands,
        Shoes,
        Peleryna,
        Shield,
        Shoulder,
        HipsTorse,
        Elblow,
        knee
    }
}